# Generated by Django 5.2.4 on 2026-07-12 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0002_technicianassigment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianassigment',
            name='technician',
        ),
        migrations.CreateModel(
            name='AssignmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_members', to='work_tracking.technicianassigment')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'worker')},
            },
        ),
        migrations.AddField(
            model_name='technicianassigment',
            name='workers',
            field=models.ManyToManyField(related_name='work_assignments', through='work_tracking.AssignmentMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
