# Generated by Django 5.2.4 on 2026-07-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0003_remove_technicianassigment_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianassigment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianassigment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
