# Generated by Django 5.2.4 on 2026-07-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0004_technicianassigment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianassigment',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicianassigment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianassigment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianassigment',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
    ]
