# Generated by Django 5.2.4 on 2026-07-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_tracking', '0005_technicianassigment_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='America/Santo_Domingo', max_length=50),
        ),
    ]
