# Generated by Django 5.2.4 on 2025-10-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Codigo',
        ),
    ]
